---
- name: Create a new user with sudo privileges "{{ item.username }}"
  ansible.builtin.user:
    name: "{{ item.username }}"
    password: "{{ item.password | password_hash('sha512') }}"
    groups: "{{ item.user_groups | join(',') }}"
    append: true
    create_home: true
    shell: /bin/bash

- name: Allow passwordless sudo "{{ item.username }}"
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^{{ item.username }}"
    line: "{{ item.username }} ALL=(ALL) NOPASSWD:ALL"
    validate: visudo -cf %s
  when: item.sudoer
